### ISSUE TITLE
Missing exercise: Single Page Applications -> Exercises -> Cars

### ISSUE THREAD

**Issue by matthamil** [nashville-software-school/front-end-milestones#53]
The Cars exercise on

https://github.com/nashville-software-school/front-end-milestones/tree/master/3-single-page-applications/exercises

results in a 404 link: 

https://github.com/nashville-software-school/front-end-milestones/blob/master/3-single-page-applications/exercises/SP_JS_ADVANCED_FUNCTIONS_CARS.md

**Comment by gregkorte** [comment]
Link to the cars exercise was removed.
