### ISSUE TITLE
Videos

### ISSUE THREAD

**Issue by matthamil** [nashville-software-school/front-end-milestones#55]
Can the videos be uploaded to Youtube or Vimeo? Currently, someone has to download each video they want to watch. 

Alternatively, could the video codecs be changed from H.265 to H.264 so they could be embedded into an HTML5 page entitled "Videos" on a gh-pages branch? H.265 isn't supported by the `<source>` tag.

TL;DR: Can we stream the videos instead of download them?

**Comment by stevebrownlee** [comment]
This change is not planned.
